// Share-link parsing for the web-client PWA. Links are generated by the
// `/share` command in the siada terminal and look like:
//   https://<host>:<port>/app?token=<t>&session=<id>&cwd=<urlencoded path>

export interface ShareLink {
  sessionId?: string;
  cwd?: string;
  token?: string;
}

/**
 * Parse share-link query params from `window.location.search`, e.g.
 * "?session=sess-123&cwd=%2Fwork&token=abc". `URLSearchParams` decodes
 * percent-encoded values (cwd paths, tokens) automatically. Params that are
 * missing or empty are simply left out of the result.
 */
export function parseShareLink(search: string): ShareLink {
  const params = new URLSearchParams(search);
  const link: ShareLink = {};

  const sessionId = params.get("session");
  if (sessionId) link.sessionId = sessionId;

  const cwd = params.get("cwd");
  if (cwd) link.cwd = cwd;

  const token = params.get("token");
  if (token) link.token = token;

  return link;
}