from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, TYPE_CHECKING
from siada.foundation.id_generator import generate_session_id

from siada.entrypoint.interaction.running_config import RunningConfig
from siada.session.task_message_state import TaskMessageState

if TYPE_CHECKING:
    from siada.support.checkpoint_tracker import CheckPointTracker
    from siada.services.file_session import FileSession
    from agents.usage import Usage
    from siada.support.spinner import WaitingSpinner
# Note: FileSession, Usage, CheckPointTracker are Optional[Any] in dataclass fields
# to avoid pulling in agents SDK (~557ms) at module load time.


@dataclass
class SessionState:
    """
    Interaction session state data model
    
    Stores state information during user interactions, complementing FileSession:
    - FileSession: Stores large language model conversation history in JSON files
    - SessionState: Stores interaction state and context information
    """

    # Core state fields
    context_vars: Dict[str, Any] = field(default_factory=dict)
    """Context variables, works with foundation.context module"""

    # Agent-related state
    current_agent: Optional[str] = None
    """Currently active Agent name"""

    # FileSession is created lazily on first access to avoid importing agents SDK
    # (~710ms) on the critical startup path.  Use the property below; do NOT access
    # _openai_session / _openai_session_factory directly.
    _openai_session: Optional[Any] = field(default=None, init=False, repr=False)
    _openai_session_factory: Optional[Any] = field(default=None, init=False, repr=False)

    @property
    def openai_session(self) -> Optional[Any]:  # runtime type: FileSession
        if self._openai_session is None and self._openai_session_factory is not None:
            self._openai_session = self._openai_session_factory()
            self._openai_session_factory = None
        return self._openai_session

    @openai_session.setter
    def openai_session(self, value: Optional[Any]) -> None:
        self._openai_session = value
        self._openai_session_factory = None
    
    # Task message state
    task_message_state: TaskMessageState = field(default_factory=TaskMessageState)
    """Task message state for managing conversation history"""

    # Recovered todo list after session resume; consumed once by SiadaRunner to populate context.todos.
    # Actual item type is List[TodoItem]; typed as Any to avoid circular imports.
    pending_todos: Optional[List[Any]] = field(default=None)

    # Recovered goal after session resume; consumed once by SiadaRunner to populate context.goal.
    # Actual type is Optional[Goal]; typed as Any to avoid circular imports.
    pending_goal: Optional[Any] = field(default=None)

    usage: Optional[Any] = None  # runtime type: agents.usage.Usage; Any avoids heavy import at module level
    
    # UI components (injected dependencies)  
    spinner: Any = None
    """Waiting spinner for showing progress during agent execution"""

    session_title: Optional[str] = None
    """Short session title generated by the fast LLM (see siada.services.session_title).
    Mirrors the terminal tab/window title so completion notifications can reference
    the same title, letting the user identify which window just finished."""



@dataclass
class RunningSession:

    siada_config: RunningConfig

    session_id: str = field(default_factory=generate_session_id)

    state: SessionState = field(default_factory=SessionState)

    checkpoint_tracker: Optional[Any] = None  # runtime type: CheckPointTracker; Any avoids heavy import at module level


    @property
    def task_message_state(self) -> TaskMessageState:
        return self.state.task_message_state
    

    def get_input(self) -> str:
        return self.siada_config.io.get_input()
    
    @property
    def openai_session(self) -> Optional[Any]:  # runtime type: FileSession
        return self.state.openai_session
    
    @property
    def spinner(self) -> Any:
        """Get the spinner from session state"""
        return self.state.spinner
