name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
        tag:
            description: "Enter existing tag to publish (e.g., v3.1.1)"
            required: true
            type: string
        test:
            description: "Publish to Test PyPI (default: false)"
            required: false
            type: boolean
            default: false

permissions:
  contents: read

jobs:
  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/siada-cli
    permissions:
      id-token: write # Important for trusted publishing to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with: 
            ref: ${{ github.event.inputs.tag }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install
      
      - name: Build release distributions
        run: poetry build

      - name: Publish release distributions to Test PyPI
        if: ${{ github.event.inputs.test == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/

      - name: Publish release distributions to PyPI
        if: ${{ github.event.inputs.test != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/